### ISSUE TITLE
Rename CSSDOM to CSSOM

### ISSUE THREAD

**Issue by JaimeIvanCervantes** [cppfw/cssom#2]
Hello @igagis, the correct name of the CSS object model is `CSSOM` not `CSSDOM`, here is is the W3C [link](https://www.w3.org/TR/cssom-1/). It's a minor thing though 😄 , but I thought that you might be interested in changing it at some point.

Also, are you planning on continuing working on CSS support?

**Comment by igagis** [comment]
I'm a bit confused now, looks like _Document_ object model is only applicable to `XML` documents, but not to, for example, `CSS` documents. See https://en.wikipedia.org/wiki/Document_Object_Model

So, `SVG` is `xml` and thus, we have SVGDOM. `HTML` -> `DOM`. But for `CSS` -> `CSSOM`. This seems inconsistent to me.
Just to mention, I also have the `jsondom` library, which, probably also cannot be called _DOM_, according to the DOM definition. But I don't quite understand why in W3C they did it that way... In my opinion CSS file is also a document, and JSON file is a document too.
So far, I think that I'd like to keep it more consistent, so, everything should be DOM, not DOM/OM. But I still need to think it through to decide what to do.

As for CSS support, I made the basic support which is enough for current tasks related to SVG, so I have no plans to implement missing things in the lib. But, help on that is always welcome. Though, in case you are going to implement some feature, please submit an issue for it first, so that we could discuss how to proceed with it.

**Comment by JaimeIvanCervantes** [comment]
I also find the `CSSOM` term confusing; when I think of the concept of a `document`, I think of a tree with nested elements, and XML/JSON based documents have an inherent tree structure. CSS in the other hand, has more of a flat structure, hence the term `CSSOM` not containing the word "document". I have seen the `CSSOM` term in every render library though, so I would suggest to use it for your lib if possible.

**Comment by igagis** [comment]
Well, that sounds reasonable. So, I think I will change the name to `cssom`.

**Comment by igagis** [comment]
`cssdom` renamed to `cssom`
